# Generated by Django 2.2.12 on 2020-04-10 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='b_price',
            field=models.CharField(max_length=4),
        ),
    ]
