# Generated by Django 2.2.12 on 2020-04-11 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0002_auto_20200410_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='b_name',
            field=models.CharField(max_length=50),
        ),
    ]
