# Generated by Django 2.2.12 on 2020-04-11 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0003_auto_20200411_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='b_price',
            field=models.CharField(max_length=50),
        ),
    ]
