# Generated by Django 2.2.12 on 2020-04-11 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0004_auto_20200411_1137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='b_name',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='book',
            name='b_price',
            field=models.FloatField(default=1),
        ),
    ]
