# Generated by Django 2.2.12 on 2020-04-11 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0006_login'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Login',
            new_name='LoginModel',
        ),
    ]
